### PR TITLE
Reduce rat blood  pool and increase cat blood pool

### PR DESCRIPTION
**Pull request by wgtjunior743**
## About The Pull Request

- Cat blood pool is now 2
- Rat blood pool is now 1

## Why It's Good For The Game

Cat is more difficult since you can get caught, they are bigger mammals, meanwhile rats are easy and safe to drink(they also literally spawn on you), much like the game they only give 1 blood.

## Changelog
:cl:
balance: Cat Blood pow is now 2
balance: Rat blood pool is now 1
/:cl:

### CODE REVIEW

**Comment by wgtjunior743** [comment]
eh i kinda messed up, i was  trying to make another pr, but it is reverted anyways.

**Comment by CatandWet** [comment]
There's enough dead cats on the road from cars and Giovanni killing them to stuff in briefcases without careless feeders killing the rest of them off.. dogs used to be the big animal with 3 blood points but these things just don't work.
Rats specifically got made 2blood in hopes there would be proper repercussions to being a ratsucker later like diseases etc; nosferatu gameplay otherwise consisted of chewing on 20+ rats so it was a bit of a bandaid.

**Comment by wgtjunior743** [comment]
> There's enough dead cats on the road from cars and Giovanni killing them to stuff in briefcases without careless feeders killing the rest of them off.. dogs used to be the big animal with 3 blood points but these things just don't work. Rats specifically got made 2blood in hopes there would be proper repercussions to being a ratsucker later like diseases etc; nosferatu gameplay otherwise consisted of chewing on 20+ rats so it was a bit of a bandaid.

We can't make stuff based on a future pr can't we? Once that disease pr is made, the person can surely modify it, also rats giving 2 blood makes them arguably better as a blood spot than humans, since they keep spawning on top of you, multiple times, giving easy blood without any chances of getting caught.
Well the nosferatu can buy blood from cargo, steal it, use mask and capture humans etc, atm sewer is just the spot also it will make chasing people easier since they could go from 5 blood to 20 there in a few minutes just from sucking rats.

**Review by Agateophobia — APPROVED** [review]
This is fine. Approved.

**Pull request merged**
