### PR TITLE
Malkav's Gift

### PR DESCRIPTION
**Pull request by Peppercorn-Z**
## About The Pull Request
Changes much of the hallucination code/sounds/sprites to be more centric to WOD13 themes and such

## Why It's Good For The Game
malkavians not having to hear lasers shooting out their woohoos is nice

## Changelog
:cl:
tweak: re-wrote large portions of hallucination code so that it's not ss13 themed
/:cl:

### CODE REVIEW

**Comment by Peppercorn-Z** [comment]
I tested this by letting it run for an hour sitting in round as a malkavian, and got no runtime errors, but it would probably be best to test-merge this before fully merging it.

**Comment by Pluvifera** [comment]
i love you for this

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 41a3b62875d85f3c07af9d8920ee8c97c180ca48
Pull Request: c59edf799957c1d05696c295b8bd370d9c171a28
Server: 5a96c11c25664fd427b076b587a0b61ad48df8cb

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 41a3b62875d85f3c07af9d8920ee8c97c180ca48
Pull Request: c59edf799957c1d05696c295b8bd370d9c171a28
Server: f955af3985a8fba62140acc5a486bd48bbd215a6

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 3a70c47a2a83bcffa32b103368adbfbda7181be5
Pull Request: c59edf799957c1d05696c295b8bd370d9c171a28
Server: 9771a1c7ff54aaf197647c693976d5065d262f35

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 92dde3cd6421af40a89614b603193f69e38ec755
Pull Request: c59edf799957c1d05696c295b8bd370d9c171a28
Server: bb45d58ceb96422752de9c721d76af1a2551815c

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: c3f591ed5386fcf537fbcc66daa900580f8fe9ab
Pull Request: c59edf799957c1d05696c295b8bd370d9c171a28
Server: 8957336ce586becbebeaed43deff76f3d62a34e7

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
