### PR TITLE
take them to the cleaners

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
some touch up the janitors

most of the unnecessary space has been reduced, in favor of a compact design
a backdoor, so janicarts do not pass through the reception 
and an additional stock room
more windows, so it looks more like a normal building
image

a crematorium downstairs away from prying eyes
a small break room was added, with a fridge, ice cream(atorium),  a free switchblade, and a crate to hold junk in
theres also sewer access, so nosferatu janitors can get in and out
image

not directly related to the janitors
but gives chunk his own "office" in millenium towers, which is also a janitors closet
image

under the hood stuff:
janitors advisors are now the camarilla, and not the anarchs, since their job desc calls the camarilla out specifically
janitors human job description changed to sound a bit better
cleaners room is now its own area and not just generically interior

## Why It's Good For The Game
people didnt like the cremator being in full view of the street
gives janitors the ability to enter and exit more discretely
less wasted space

## Changelog
:cl:
change: cleaners office
add: janitor area tile
change: some janitor stuff
/:cl:

### CODE REVIEW

**Review by AllCorruptingWyrm — COMMENTED** [review]
This will cause conflict issues with https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/286

**Comment by Odisurin** [comment]
> This will cause conflict issues with #286

We can hit that road when we get there, is this not in the northern section of the map anymore?

**Comment by Agateophobia** [comment]
> > This will cause conflict issues with #286
> 
> We can hit that road when we get there, is this not in the northern section of the map anymore?

Map conflicts are relatively easy to resolve too.

**Review by Agateophobia — APPROVED** [review]
Approved.

**Pull request merged**
