### PR TITLE
All-in-one Wolfing

### PR DESCRIPTION
**Pull request by CatandWet**
## About The Pull Request
Check old changelogs for majority; mostly flattened numbers back down after looking at their sturdiness, without the broken rage heal equation in factor they feel much better in tests.
Heal does about ~70 heal a pop every 15s. Universally lowered garou ability cooldowns from 20s to 15s.

+Garou now no longer a bit too unkillable while retaining ferocity
+ 100% sharpness gets the boot alongside other claw adjustments, a limb on every street corner is no more

Currently feels good enough for actual testing.

+ Later addition of late party number corrections, they were old values more designed for 50+ pop.

## Why It's Good For The Game
A more fair chance for wolves to not be ground into paste.

## Changelog
:cl:
del: My patience for writing changelogs
tweak: numbers go look and give feedback instead of scream at me
/:cl:

### CODE REVIEW

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: 5af1a24341bb49712484eef52cd53ecd8dba7e6b
Server: 7c46e0e1d06eb732e0710b1ce3a6cf8696ba4a6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: d6c3e002a36f734cd960736d3a4eaaf94b93ada2
Server: c617ccc7e7ec2bd8c1b952fd29dad7cfdad6b395

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d771eff57ac66390a21bf42ed739bf4401245c94
Pull Request: d6c3e002a36f734cd960736d3a4eaaf94b93ada2
Server: 1aceb342b06dcd69f85813896c46e41c6e6d7977

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: f11d730dc8f40847e5db24f04e566786ce422559
Pull Request: d6c3e002a36f734cd960736d3a4eaaf94b93ada2
Server: 51a5414e1ea889322c7bc30d6d56e74a3f12925d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 19eceb306bb90eda702a8e494992e77a047f9e5f
Pull Request: d6c3e002a36f734cd960736d3a4eaaf94b93ada2
Server: 7783213fd0f6be45bbaeefa47db34503846ad672

##### Comment

</details>

**Comment by Cre77** [comment]
iirc (unless it's been fixed) werewolves in old vtm were utterly ROLLED by anything related to blood. getting bit knocked them out instantly in human form, making sneak attacks miserable. tremere blood theft was also unmanageable - you could not regenerate blood in your transforms, and the moment you hit 0 (which was just a few casts) you died instantly and unrevivably.
they also had big issuse with organ damage (and limbs also) - getting any sort of organ damage would put you into permanent crit and a slow death that you can't heal out of without surgery, which often led to you having to stay in your wolf form to avoid dropping dead when reverting after an ambush

**Comment by CatandWet** [comment]
I was aware of the fatal vicissitude weakness/outright buggy interaction that just insta-drops garou (not sure if still happens with bigger hp pool, it likely does..) but the blood issues I guess could be remedied by just giving the werewolf human species slightly bigger blood pool/or give them a latent one bloodpoint regen every 5-8min or something possibly? So if they do get all their blood stolen it's not as debilitating and if left alone in crit they'd be able to get on their feet to go to the hospital eventually rather than stay stuck in permacrit.

Unless there's some trait or mutation that I can easily give garou human form to have less organ failure/damage but still be affected by it somewhat, I'm not quite sure what to do about that part.

**Comment by Cre77** [comment]
i feel like giving all their forms a bigger bp pool and making rage heal regen a point of bp, organs and limbs would solve a lot of these problems
not getting ko'd as easy on homid would help, too

**Comment by CatandWet** [comment]
> i feel like giving all their forms a bigger bp pool and making rage heal regen a point of bp and restore organs would solve a lot of these problems not getting ko'd as easy on homid would help, too

I can do the bigger blood pool that shouldn't mess anything up, and while those other two should be easy to add I'm less confident doing those changes; rage heal does already clears wounds would just need to make it more similar to bloodheal which heals various issues a human mob might have; blindness/dizzyness/organ dam/all sorts of stuff.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 52e5967f44f7e1e1fa9187c5c9d8a08651a3cb17
Pull Request: d6c3e002a36f734cd960736d3a4eaaf94b93ada2
Server: 05cfa1d6c63b0d6a14d4c15d54d7e890c4986936

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 8e319901f1cc7d151100c14c45028a6f1cf3c67a
Pull Request: b177aa76efe34377363bf3b13e2caf5664cf436d
Server: 55960fd6585c69e06d5526982d8f06b8906dfe45

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: d81c23dc885d585bcf86c8071e7988b3f51604c7
Pull Request: b177aa76efe34377363bf3b13e2caf5664cf436d
Server: e9e2dac000c0529406bcdf6b0be2adfdd0d35f0b

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: a116d7a3a557a5ee636b3d74e8751b10086fe176
Pull Request: b177aa76efe34377363bf3b13e2caf5664cf436d
Server: 0cbaaeba01f9c96ff58eff6e3396276888e55aab

##### Comment

</details>

**Review by Agateophobia — APPROVED** [review]
Didn't produce any negative feedback during testmerge, worst case scenario will get readjusted in another PR.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: dc0fdc04c3ff089b81c61f11ab55b723dd9dbefa
Pull Request: b177aa76efe34377363bf3b13e2caf5664cf436d
Server: ef9e8078c16ef0005fbcf7295b93d4d13bc5f54e

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
