### PR TITLE
Generation nerf

### PR DESCRIPTION
**Pull request by Phenomeus93**
This is mostly for testing purposes. 

## About The Pull Request

Tweaking values that Generation gives.

## Why It's Good For The Game

In tabletop generations do not give out additional health, and any blood pool they increase is by 1. This is supposed to level out the field between higher and lower generation somewhat, there is no point staying high generation for roleplaying purposes when lowering your generation is such a boost.

## Changelog
:cl:
tweak: tweaked a few things
balance: rebalanced something
code: changed some code
/:cl:

### CODE REVIEW

**Comment by Agateophobia** [comment]
Please fill out the PR template properly (including a changelog), it's here for a reason.

**Comment by Phenomeus93** [comment]
> Blood pool in tabletop doesn't really follow a formula. In its current state you've nerfed blood pool to below tabletop rates because of the jump at 7th gen

Generation 7 bloodpool gives 20 instead of 16, i am aware of that and i willfuly chose to ignore it since i consider generation 7

**Comment by Agateophobia** [comment]
Are you still working on this?

**Comment by Agateophobia** [comment]
Since this is clearly not being worked on, I will close the PR. 
Feel free to make a new one whenever you're done with this.

**Pull request closed without merging**
