### PR TITLE
COPS AND ROBBERS

### PR DESCRIPTION
**Pull request by Plaguewalker**
## About The Pull Request
Adds Kindred to Triad, along with adding garou to the PD 

## Why It's Good For The Game
Garou have been in need of more love in terms of roles to play, and while I would love to add cop vampires this is as close as I can get. In exchange for kindred being added to triads to buff the survivability of the human members it, to reinforces the cops survivability with garou on the force. 

## Changelog
:cl:
add: Added new things

### CODE REVIEW

**Comment by SixplyDev** [comment]
Erm... garou were already added to the PD in another PR

**Comment by SixplyDev** [comment]
https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/338

**Comment by faaaay** [comment]
Not a fan of adding kindred to the Triad, because I can only forsee them being completely dominant in the faction.

**Comment by Plaguewalker** [comment]
> Not a fan of adding kindred to the Triad, because I can only forsee them being completely dominant in the faction.
I'll limit to only one so it's not an overbearing situation, where they'd still be outnumbered by the humans.

**Comment by spartanyanni** [comment]
Consider just - Not adding them at all?
Maybe keep a literal single faction without any vampire slots, possibly?

**Comment by lucifernix** [comment]
Not fond of either garou in the PD or Triads having kindred, personally. At least, when I initially added the triads, they were meant as a human-only faction and to stay as one, perhaps gaining a tie with some kuei-jin if they were to ever be added in the future.

**Comment by Plaguewalker** [comment]
> Not fond of either garou in the PD or Triads having kindred, personally. At least, when I initially added the triads, they were meant as a human-only faction and to stay as one, perhaps gaining a tie with some kuei-jin if they were to ever be added in the future.

The problem with kuei-jin it muddles things a bit further, and I don't really want to go out of my way to get kuei-jin added for what already is a messy system of checks and balances. If and when things are stable enough I'd get them added but, right now I have no real idea on properly translating them to ss13's code

**Pull request closed without merging**
