### PR TITLE
Adds a new machete weapon

### PR DESCRIPTION
**Pull request by Spefo**
Adds a new machete weapon

## About The Pull Request

Adds a machete that is weaker than the katana but takes less space, it does good throwing damage too
## Why It's Good For The Game
More weapons, more fun

## Changelog
:cl:
add: Added new machete weapon, and also buyable on cargo

/:cl:

### CODE REVIEW

**Comment by SpaceSlug2** [comment]
i'd lower the AP, asides that, its kino.

Uploading Christmas_message.mp4…

**Comment by Spefo** [comment]
> i'd lower the AP, besides that, its kino.
> 
> Uploading Christmas_message.mp4…

Lowered!

**Comment by SpaceSlug2** [comment]
its peak..

**Review by Agateophobia — APPROVED** [review]
Approved. Loved. Appreciated. Merged.

**Pull request merged**
