### PR TITLE
Adds a few small additions

### PR DESCRIPTION
**Pull request by Odisurin**
A bunch of the map felt off and there was some items that hit me with too much Slavjank, so I did a few minute changes that only effect viewing of the world, Such as Lowering the speedlimit for realism rp, and adding more ATMS to make it not just super inconvienient..
All else change as I was working on the main things that drew me to changing things "street signs"..

Changelog
🆑
add: adds a new 25 MPH sign, places them on the map completely within the city limits
add: adds a pre-existing 40 MPH sign
add: more ATMs to the map, one in an alleyway in pacific heights, a far ATM in Chinatown in the housing district, ATM in the far south of Chinatown, a ATM near the boardwalk right near the stairs, ATM behind the Jazz club in an alley, ATM directly in the Millenium Tower, ATM in the PD lobby, ATM on the far east of the map near the arrival tunnel, ATM south of Archive in a alley, ATM located at the Boardwalk in an alley beside a grocery store south of the other, ATM outside anarch bar, clinic ATM
add: new red aviators
add: adds three boxes of face masks to the hospital, one in the lower basement abandoned checkpoint, lower storage, and the above storage.
add: stethescope to the hospital, about three within it (This could be tweaked since its an instant heart check)
add: adds in a few new sinks to the map including one in the janitorial location.
add: mask vendor with the option of bee, fox, bat, rat, mummy, surgical, and jackal.
add: adds three mask vendors around

tweak: tweaked the Chicken nugget to be called a Chicken wing
tweak: sprite color for medical bag onfloor sprite to be more inline with the inhand object and on mob
tweak: changes the name and description for pizza
tweak: changes crisps to the proper american word chips
tweak: all descriptions to order menus to be properly made
tweak: changes order menus to Clerk Catalogue
tweak: changes the cola bottle to a Two liter bottle

del: a few old 50 MPH signs
del: three old clothing stores

/:cl:

### CODE REVIEW

**Review by Agateophobia — CHANGES_REQUESTED** [review]
For the love of god, use the provided PR template or for the very least write down a changelog properly.

**Comment by Odisurin** [comment]
## Changelog
:cl:
add: adds a new 25 MPH sign, places them on the map completely within the city limits
add: adds a pre-existing 40 MPH sign
add: more ATMs to the map, one in an alleyway in pacific heights, a far ATM in Chinatown in the housing district, ATM in the far south of Chinatown, a ATM near the boardwalk right near the stairs, ATM behind the Jazz club in an alley, ATM directly in the Millenium Tower, ATM in the PD lobby, ATM on the far east of the map near the arrival tunnel, ATM south of Archive in a alley, ATM located at the Boardwalk in an alley beside a grocery store south of the other, ATM outside anarch bar, clinic ATM 
add: new red aviators
add: adds three boxes of face masks to the hospital, one in the lower basement abandoned checkpoint, lower storage, and the above storage.
add: stethescope to the hospital, about three within it (This could be tweaked since its an instant heart check)
add: adds in a few new sinks to the map including one in the janitorial location.
add: mask vendor with the option of bee, fox, bat, rat, mummy, surgical, and jackal.

tweak: tweaked the Chicken nugget to be called a Chicken wing
tweak: sprite color for medical bag onfloor sprite to be more inline with the inhand object and on mob
tweak: changes the name and description for pizza
tweak: changes crisps to the proper american word chips
tweak: all descriptions to order menus to be properly made
tweak: changes order menus to Clerk Catalogue
tweak: changes the cola bottle to a Two liter bottle

del: a few old 50 MPH signs

/:cl:

**Comment by Odisurin** [comment]
I have no idea how to add this to the actual PR, unless I hit draft?

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 4d4c13323a90280f721794387c276642bafede75
Pull Request: d3f7457b52541fd4e535ac61c0a76e3ad0586d7e
Server: 51c7f4f48979240b92d429ca38fd8318cf4f23ce

##### Comment

</details>

**Review by lucifernix — APPROVED** [review]
Everything seems to work and be in order after a test. So I will approve this.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: ee21ecba94590df8ddda1a11f400fca40f665984
Pull Request: d3f7457b52541fd4e535ac61c0a76e3ad0586d7e
Server: bc198530be5aba7189e1c005e15228fa5b046cc3

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
