### PR TITLE
Kiasyd [ready] 👽👽👽👽👽👽

### PR DESCRIPTION
**Pull request by Discozavisim**
## About The Pull Request

bogos binted?

## Why It's Good For The Game

👽👽👽👽

## Changelog
:cl:
add: Added Kiasyd and mytherceria
add: Added Gangrel and Tzimisce clan accessories
soundadd: added mytherceria sound
imageadd: added some clan accessories and discipline icons
code: changed some code in preferences
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
I think you should really state what each of the powers do, what they get, etc etc. Otherwise ppl have to code dive and will get confused.

**Comment by Plaguewalker** [comment]
> I think you should really state what each of the powers do, what they get, etc etc. Otherwise ppl have to code dive and will get confused.

Fae Sight -  Tells you each item the victim has, plus backpack. Metal items will have red font, magic items will have green font.

•• Darkling Trickery -Allows you to steal an item from the victim plus dexterity/mentality check. Projects them inverted controls, so WASD will work opposite for some time. 

••• Goblinism. Summons a goblin beastmaster companion that'll instead of attacking steal victim's weapon, if there's no weapons then the helmet, and if victim doesn't have a helmet the goblin sits on their head blocking sight.

•••• Chanjelin Ward - Pretty simple one, floor trap that causes a wide array of disorienting status effects/allows you to pick which trap to set via summoned scroll

••••• Riddle Phantastique - You can do a custom riddle, and decide options it has (including the right one). If victim chooses fail option minimum half of times there are fail options - the victim looses their tongue organ. Till the riddle is solved the victim talks backwards

**Comment by UltraBigRat** [comment]
Maybe give them the option for dominate instead of necromancy? Since that is a thing they also have in the lore as the usual discipline, and would fit their kit pretty well with the ability to make people forget things and such, without stepping on giovannis toes.

**Comment by darkincarnate** [comment]
Is there a picture of what the Kiasyd curse looks like? Also, what are the different effects you can put on your traps?

**Comment by Plaguewalker** [comment]
> Maybe give them the option for dominate instead of necromancy? Since that is a thing they also have in the lore as the usual discipline, and would fit their kit pretty well with the ability to make people forget things and such, without stepping on giovannis toes.
Dominate is a disc that can for the most part be picked up by anyone and really practically it's kind of useless depending on spec. Adding to the fact dominate itself with everyone and their mother is using wiseman it would be a waste in all honesty. I chose necro primarily now there's another clan outside of the giovanni who can wield it.



> Is there a picture of what the Kiasyd curse looks like in-game? Also, what are the different effects you can put on your traps?
When examining items that you can touch it would show a red or green text of _**x can be picked up or not.**_

**Comment by darkincarnate** [comment]
By curse I mean the downside of them being tall, lanky and having dark pupils for eyes.

I see no problem with them using necromancy, Giovanni can have a problem with it IC if they want.

**Comment by AllCorruptingWyrm** [comment]
they got their bogos binted.

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: 02c5f422b8ad2f7a286c9bd75abc09570d6f2c74
Pull Request: b8b48b4ce549fa290165d5aebbf552363f5032ca
Server: 71bb967830a79aeb0838f0305f3a59a2db906d0d

##### Comment

</details>

**Pull request merged**
