### PR TITLE
Salubri discipline changes

### PR DESCRIPTION
**Pull request by lucifernix**
## About The Pull Request
Salubri 2nd discipline is no longer going to instantly handcuff you, and the 4th will no longer instantly drain your entire bloodpool. 5th also does not revive the dead any longer.
Instead, the 2nd discipline allows you to make a kindred drowsy and a mortal to fall asleep for 30 seconds. 4th discipline allows slightly better healing than 3rd, and gives you the ability to create walls around yourself for protection for a short time.
5th discipline allows you to increase the humanity of other kindred.

## Why It's Good For The Game
It nerfs an extremely overpowered auto-win discipline and makes it more lore accurate.

## Changelog
:cl:
add: redid half of the valeren discipline
del: deleted some old valeren powers
/:cl:

### CODE REVIEW

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: d549ea4b2916c76a55649ee203538d27120d9351
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 813239e80d38a13beb9a6a89c2133078ec373670

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: ca6ba0e45402f2cf78ae3315847376070a42ce0f
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 4550117a85ecce9b69b9ed253b15cac20a2a902e

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: ecef66fe25d0f156b312f49a294cc5cf38ddd366
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 386ab8ccd83ec3c6c738b52dcda629c178520952

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: c5f89bf87eb19ecc37cad75f12aaab866d9fd41e
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: a3d055cba8ea297398f6b904a0e860615cffa6bd

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: b99d72f11ac8aed5676ca5f86ee668221e3aca0d
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: f2b57885c5295433124270b8c3a318005f412546

##### Comment

</details>

**Comment by MercuryArrow** [comment]
The only other feedback I would give to this after using it a bit is that it could be worth letting the Valeren 1 scan power inform you if someone's on Humanity or not and maybe a very vague statement about whether they're in a good position or gettin' low.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: d3c9b63ae64f0bc15d8817d6b2b2bb17834e990e
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 3c5e60d2126f63615432b03866e977a625a53711

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: 0b533173e3da471cf29372b905c643c4bb3e8f35
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 8501d9cb027bee7f714812d40a6758a19619e8d7

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: 54eac3256d75e0e3214f67f311f80c958d2dd2ee
Server: 1ee52800c7e2506d3d48f245c1541a01b18221d6

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: b170975850a36ad66ff2758c53bdd87efdac3c4e
Server: ecaf0d09eb36eb8991ef587ed8a4d713e30b5f6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
