### PR TITLE
Add a reason to your bloodhunt

### PR DESCRIPTION
**Pull request by lucifernix**
## About The Pull Request
Small QoL of life feature. But since when do you execute someone just for funsies? All royalty gets to proclaim the reasons for which they execute their enemies.

## Why It's Good For The Game
It gives more context to everyone about why someone is getting blood hunted, as blood hunts are a very serious thing. It will make people less... uncaring about them as well, if they know the reasons.

## Changelog
:cl:
add: Added ability to list reason for bloodhunt
/:cl:

### CODE REVIEW

**Comment by faaaay** [comment]
How does this interact with the Sir, You Are Beind Hunted quirk?
image

**Comment by lucifernix** [comment]
> How does this interact with the Sir, You Are Being Hunted quirk? image

It would give the "no reason provided" upon the announcement of the bloodhunt. I suppose that can be altered if you provide suggestions.

**Comment by faaaay** [comment]
> > How does this interact with the Sir, You Are Being Hunted quirk?
> It would give the "no reason provided" upon the announcement of the bloodhunt. I suppose that can be altered if you provide suggestions.

Oh! Sorry, I didn't put that together. Nah, no objections/suggestions here, just wanted to make sure that was covered.

**Comment by lucifernix** [comment]
Actually you were right there was no reason provided, it was just blank. Thanks for pointing it out. It should be this now.

https://i.imgur.com/ggx4gER.png

**Pull request merged**
