### PR TITLE
Replacing omniscience Auspex 5 with more lore accurate auspex 5 (2)

### PR DESCRIPTION
**Pull request by lucifernix**
## About The Pull Request
Makes it so Auspex 5 lets you move around and observe. Disables some observer features, adds a requirement for you to find your body before re-entering it. Does not have the silver cord.
You can't see the regular ghost verbs you have no access to either. Nor respawn while in auspex mode. Can't hear or talk to ghosts either, and auspex users display a different message while observing.

## Why It's Good For The Game
It will disable the extremely overpowered omniscience feature with one that is more workable.

## Changelog
:cl:
add: Added more lore accurate auspex 5
del: Removed old auspex 5
/:cl:

### CODE REVIEW

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: e89a1d9a55debfd36282182431485a9073a38c7b
Pull Request: 2050db9438829038d39d546cb1cc451073a09790
Server: d29cf44ebf1cece29ca495c579936c4e490c56cd

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: d549ea4b2916c76a55649ee203538d27120d9351
Pull Request: 2050db9438829038d39d546cb1cc451073a09790
Server: f3dbfb80b444e8898fe1f8b8031e31870051734d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: d549ea4b2916c76a55649ee203538d27120d9351
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 813239e80d38a13beb9a6a89c2133078ec373670

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: ca6ba0e45402f2cf78ae3315847376070a42ce0f
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 4550117a85ecce9b69b9ed253b15cac20a2a902e

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: ecef66fe25d0f156b312f49a294cc5cf38ddd366
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 386ab8ccd83ec3c6c738b52dcda629c178520952

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: c5f89bf87eb19ecc37cad75f12aaab866d9fd41e
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: a3d055cba8ea297398f6b904a0e860615cffa6bd

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: b99d72f11ac8aed5676ca5f86ee668221e3aca0d
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: f2b57885c5295433124270b8c3a318005f412546

##### Comment

</details>

**Comment by Plaguewalker** [comment]
Personally, not a fan of the observer change as a whole... I would've said maybe make Aus 5 cost more thus preventing the spam and slightly nerf the uptime down by a big margin.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: d3c9b63ae64f0bc15d8817d6b2b2bb17834e990e
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 3c5e60d2126f63615432b03866e977a625a53711

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: 0b533173e3da471cf29372b905c643c4bb3e8f35
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 8501d9cb027bee7f714812d40a6758a19619e8d7

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
WoD13 Live

##### Merged By
Lucifernix

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: 1ee52800c7e2506d3d48f245c1541a01b18221d6

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: b60b98506d35dd80703a1de2ede6ec0e0165f0d0
Server: ecaf0d09eb36eb8991ef587ed8a4d713e30b5f6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
