### PR TITLE
buckshot addition

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
adds 12ga buckshot to test out
fires 8 pellets at 9 damage each for 72 damage at point blank, so TTK of 2 hits against unarmored targets to knock them down, 4-5 at about half a screen away
buckshot is available to buy from cargo and gun store

## Why It's Good For The Game
they asked for it
two-tap hoodlums

## Changelog
:cl:
add: 12g (00 buck) shell and associated pellet
add: box of 12ga (00 buck) and icons for them
add: box of 12ga (00 buck) can be purchased
change: range reduced on shot shells to 22, so pellets despawn sooner, to reduce the odds of accidentally aggroing half the city
change: shotgun description now accurately says it has a 6-round tube
change: renames shotgun bullet to shotgun shell

/:cl:

### CODE REVIEW

**Comment by CatandWet** [comment]
Only one thing I'd change with the prices otherwise looks pretty good, and your testing confirmed it seems to work alright.

**Comment by cornercube** [comment]
> Only one thing I'd change with the prices otherwise looks pretty good, and your testing confirmed it seems to work alright.

changed to 400 on both vendors, for consistency with slug

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 78d621554a4d84f6272e92d3ec171462f46e3037
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 4c350d4b9e538734f6916a726bf701136432c36d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: fd7ac29018903cabf2d16690b99f0318bd64de49

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 7c46e0e1d06eb732e0710b1ce3a6cf8696ba4a6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: c617ccc7e7ec2bd8c1b952fd29dad7cfdad6b395

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d771eff57ac66390a21bf42ed739bf4401245c94
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 1aceb342b06dcd69f85813896c46e41c6e6d7977

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: f11d730dc8f40847e5db24f04e566786ce422559
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 51a5414e1ea889322c7bc30d6d56e74a3f12925d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 19eceb306bb90eda702a8e494992e77a047f9e5f
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 7783213fd0f6be45bbaeefa47db34503846ad672

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 52e5967f44f7e1e1fa9187c5c9d8a08651a3cb17
Pull Request: a68cafd73e08d17bee0dab3ac719779d3ed44b25
Server: 05cfa1d6c63b0d6a14d4c15d54d7e890c4986936

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Review by Agateophobia — APPROVED** [review]
Seems alright, there was no negative feedback from the testmerge, merging.

**Pull request merged**
