### PR TITLE
Cars [Final cut by Flavrius] TEST

### PR DESCRIPTION
**Pull request by Discozavisim**
## About The Pull Request

Cars

## Why It's Good For The Game

Cars

## Changelog
:cl:
add: New car and steering mechanics that makes them super smooth and way less painful to drive.
/:cl:
image

### CODE REVIEW

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: dd5fe7397d65eb14503118ca9cdc1392f6d9be66
Server: 4a88b4d93e65c8ad4a4fcc16cedb376f091eb245

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: 6108cf43d5eca1759a210e91c52cf37cf92b06ba
Server: 70b559d8026f7aa060d1795b797d6d15eec76387

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: 52fd6868a4ad8586cf4df523ebbf2c272a26a516
Server: aaae655ad3a8991494fc885074abdac795e76197

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b3764f585146b8d27d65632664ba51d62c2687b1
Pull Request: 52fd6868a4ad8586cf4df523ebbf2c272a26a516
Server: 30a1ed8d274d89330ef7bb43a0e6f29b69f18965

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: 140fc110031c1809572241fb2e386150a23f1f04
Pull Request: 52fd6868a4ad8586cf4df523ebbf2c272a26a516
Server: 55cb240cd57be31db2fccd0126c68eed579e2108

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 140fc110031c1809572241fb2e386150a23f1f04
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: e31b5a459f058af586f7312e878f6742b774f1f2

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Agateo

##### Revision
Origin: 93eb1384bf5014caa1d3f3a3a7dd8fb73148f4c9
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: 8c9e7af1d3500beb2c14f7f4aff4125bab4698fe

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 4d4c13323a90280f721794387c276642bafede75
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: 51c7f4f48979240b92d429ca38fd8318cf4f23ce

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: ee21ecba94590df8ddda1a11f400fca40f665984
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: bc198530be5aba7189e1c005e15228fa5b046cc3

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: ee21ecba94590df8ddda1a11f400fca40f665984
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: 3d0d27719b1be60c2d6f95ec2f4e2a100da9462a

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 7425bbb92c4824da6e24f9d9c5fd2bd294289efe
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: b8c43722419295c26f7b3274fef4ca2ee2c3fc61

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 7425bbb92c4824da6e24f9d9c5fd2bd294289efe
Pull Request: ac0d3c7a1f3c66c69f52f99a58f5a76e4adc14d6
Server: a08b8c095dbf5c5c4348d9a71916e5f2e33daf9a

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 7425bbb92c4824da6e24f9d9c5fd2bd294289efe
Pull Request: 2ffac61a2ea5c99ee99b8bb98264eb93aeb82ba2
Server: 438b1908b99cd53620987d0bf7fa95031c8b1395

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Agateo

##### Revision
Origin: 7425bbb92c4824da6e24f9d9c5fd2bd294289efe
Pull Request: e2e38877fe849612768786a74379e14ef0ea4351
Server: 79258fcf98a5b6a84535525a14f6cb87041ceacd

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Agateo

##### Revision
Origin: 9224e0387571d4a4441d12fc365f97848fd5c4a3
Pull Request: e2e38877fe849612768786a74379e14ef0ea4351
Server: ffbc3d9d2a96d6f27907dc8d53b4e46f28242e73

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Agateo

##### Revision
Origin: b7528cc36f46669aec09d93f3a512a37ea358bea
Pull Request: e2e38877fe849612768786a74379e14ef0ea4351
Server: 4f3c9ba13440bbc8031219e2835248c0069ccbc8

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b7528cc36f46669aec09d93f3a512a37ea358bea
Pull Request: 9354a890d41372a3607d26b502f0c1702b3ba8f9
Server: 4be79b3027d1a940ecbb0796ef8fc4ebc0363a77

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b7528cc36f46669aec09d93f3a512a37ea358bea
Pull Request: 9354a890d41372a3607d26b502f0c1702b3ba8f9
Server: e91d5db65a2074d587c22752622b5598f8e8862e

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: 4db8234d9e2d5c9cdda6295b8d3183d8f75e81d5
Pull Request: 9354a890d41372a3607d26b502f0c1702b3ba8f9
Server: 1697e5eae469aea2b701a61867c42f58d850244a

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: 4db8234d9e2d5c9cdda6295b8d3183d8f75e81d5
Pull Request: 9354a890d41372a3607d26b502f0c1702b3ba8f9
Server: 92c1a8154172192b15c89a78f6bda5610fe57673

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: 4db8234d9e2d5c9cdda6295b8d3183d8f75e81d5
Pull Request: 9354a890d41372a3607d26b502f0c1702b3ba8f9
Server: 640725803a2038f480a201a61d1641989690df24

##### Comment

</details>

**Comment by CMDR-Gungnir** [comment]
Having played with it a bit on the test server, the ambulances are unable to be driven out of the Hospital bay.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucia

##### Revision
Origin: b072d43bb3288c66e2d456018dda79930cbafbbe
Pull Request: b9ac568ca7be64095876637c13115183083a9b77
Server: 2c3ab8743e91a916273a55ac2daeb2bba3641253

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
