### PR TITLE
[TEST MERGE ME PLEASE] Puts Garou in the bin forever

### PR DESCRIPTION
**Pull request by CatandWet**
## About The Pull Request
**PROBABLY READY FOR A TEST MERGE TO MAKE ALL THE GAROU MAINS CRY**
I really need live testing for a lot of this since it's insanely hard to test a lot of this local.

Cuts down the absurd values that had crinos form being too insane of a mix of hp, armour (which was nullifying damage weaker than the werewolf_armor value seemingly?) and speed. These are a middle ground between the old values garou's crinos form had on the ru server and what they are currently.
Tones down hispo's speed and bite power. 
Adjusts some rage/gnosis costs of gifts or swaps some auspice gift's cost from using gnosis to rage without making them unusable for certain breeds forms/too heavy of a rage cost to use in battle.
+ Attacks the paralyze var so glasswalker zap isn't as stupid (credits to the other wolf PR I was rude to) From testing not sure this changed much since the AOE lightning isn't paralyze anymore.
+ Adds a slowdown to silver and gives each bullet clone damage while adjusting added brute per bullet. (80% sure crinos form can't be stunned so a 1s knockdown might be needed later if slowdown isn't potent enough.. **TESTING IMMOBILIZATION INSTEAD**) 

+ Buffs some melee weapons slightly because I was in the melee.dm changing garou stuff.

+ Gives all garou in crinos form a small amount of clone damage per swipe; be gentle to kindred they don't like aggravated damage.

+ BSD toxin claws fixed thanks to luci, ahroun razor claws given slight aggravated too, both gifts rebalanced.

+ Garou made properly vulnerable to toxin damage instead of entirely immune (BSD should probably be more resistant to it but that can come later)

## Why It's Good For The Game
GAROU NERF GAROU NERF GAROU NERF GAROU NERF THE KINDRED SUFFER THE HUMANS SUFFER GAROU NERF GAROU NERF 

## Changelog
:cl:
tweak: numbers because that's the only thing I'm good for
balance: non-existant
/:cl:

### CODE REVIEW

**Comment by Plaguewalker** [comment]
Screw these nerfs altogether the same with the other PR https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/314. People bitch because they get their shit pushed in when garou are meant to be a credible threat to kindreds as a whole. And, given how rampant some fuckers are in openly killing it at least provides a buffer in dispatching those ones pushing things to far when they overstep into the wolfs den. Nerfing them is basically the most asinine way of going about this because some get upset over the stun which was already nerfed

**Comment by SpaceSlug2** [comment]
https://github.com/user-attachments/assets/9c2ef09d-993e-4c58-bc96-26116192870c

**Comment by CatandWet** [comment]
if I just comment out the glasswalker tribe entirely will this get test merged faster? :crying_cat_face:

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 2b5cc50e978ed9ee6d61703da802f1381fb9697c
Pull Request: 766e3476432ed4499f86e7ea7e2c9f033d59a8d5
Server: 5fd1581489efdf3cbee0c843c0f35c649db39d3d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 2b5cc50e978ed9ee6d61703da802f1381fb9697c
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: ed79019f88dcc2a7c1812a316bd8520413f46a6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 945ebacebaad6f5e7b9f9a6f8ff46783b44b7dc4
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: 9b089bdba531fc152e471b0a594113b5254dd388

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 28ff598464e313852c508ddc9d9d52248ba5e727
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: 3a7bc67e8f2627352f707bcd2c1732f390a7994a

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 736753b547dc09648e4c8bdb95ae417c70e6faf4
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: d2d968d1d68a2f5a569dc2467ae4b9d126898a1b

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 44c1f69f83d8ba6b1b0c8c3257a994b5ea627951
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: 62daf43cb26f358c6ef2a263500079766abbb206

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: f68821436343b5a888207ecd38687b052dcfc4b0
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: ee36c7c9a8ee6310cf88d8d2656de0a28ea58ae4

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: bf19e7ba8aad90208c0a59408248c245d9b061c7
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: 076fe868431b5d4831b6e8f58c4430c2ad64794d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 5ac63a964f90d80c113c48028b551f10f5aabdaf
Pull Request: 9b37f40904db9bdc48037f557ad16c5a24866d36
Server: 40e8a2a250441c996091dd3257476ac72c24e52b

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
