### PR TITLE
Adds sprites and a few map changes

### PR DESCRIPTION
**Pull request by Odisurin**
add: adds A bunch of new sprites for various different ingame items and utilities made by Flav (pay phones, surgery chairs, and washing machines have been switched) the rest are vending machines, angel statue, more cave floor sprites, adds the dry arid dirt floor sprites too, more item sprites all within the weapon.dm file (No onmobs yet)

add: gives bone gel/surgical tape to medical

adjusts: adds windows to the bottom floor of medical to allow for less boxed in feel

add: gives medical potted plants

add: recharger to bottom floor of medical backroom, and a charger to the top floor lobby.

adjusts: moves some roller beds to the side to give room for two sinks

adds: two sinks to the medical surgery room

adjusts: changes the ATM sprite to be Flavs smaller newer ATM sprite

adds: ATM to the alley above trainyard

adjusts: chaplain's church to have an office for him on topfloor and a removal of the pot room

add: large 3x1 windows in the church for the time being along with rooms in the bedrooms

add: an extra door to the church on the side that was unused.

code: adjustments of the file path and icon name for ATM's, surgery tables, washing machines, and pay phones

add: places a mask vendor in the Nosferatu slum town right at the front (The guy is a blind hobo)

add: puts two freezes in the slum area of the map for fluff and for the odd sort that want to put their beers in a stained cooler

### CODE REVIEW

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: 8e22103e1b5ab286f682ed8c3c4cbe931cf9896f
Pull Request: 9117731a537a93b4d535345a96a38cd8db0272e4
Server: 989e25ac391fd7b1c547b3f1ff29156b2d392dcd

##### Comment

</details>

**Review by lucifernix — CHANGES_REQUESTED** [review]
https://i.imgur.com/kGehmso.png

Please make the side facing ATMs not stuck in the walls. Also please rotate the surgical tables at the hospital.

Other than that looks good.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Test Server

##### Merged By
Lucifernix

##### Revision
Origin: ea6b48dc135f53a539209b9332a463f654183b72
Pull Request: 9117731a537a93b4d535345a96a38cd8db0272e4
Server: cfa808decef5ecf70e42471c660cdea757393640

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
