### PR TITLE
Calibre Tweaks

### PR DESCRIPTION
**Pull request by CatandWet**
## About The Pull Request
Messes with gun balance but keeps most damage values similar while tweaking arpen and adding varying amounts more general wound chance and firing against an unarmoured limb wound chance to firearms for potentially more slowdown per wound inflicted and better niches filled.
Different guns with burst spray tighter/wider cones.
MP5 magazine from 25 to 30.

Both this and the melee changes could really use some proper testing, hard to get a feel of real balance with wider scale fights happening rather than me shooting at NPCs for test dummies.

## Why It's Good For The Game
It felt unfair to focus on just melee weapons.

## Changelog
:cl:
tweak: Slugs will sting slightly more.
tweak: Crossbow toned down.
balance: Other ammo types
balance: Guns changed to hopefully accommodate more variety.
/:cl:

### CODE REVIEW

**Comment by Peppercorn-Z** [comment]
why are we adding wound bonuses to virtually every bullet type 👀 
You're also nerfing crossbow bolts while making everything else do more damage
Crossbow bolt is 3 single shots then you have to reload each bullet individually
you also added stagger to shotgun shells.

Stuff like this needs to be tested extensively before being merged, because it has **Massive** gameplay implications.

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: 7c46e0e1d06eb732e0710b1ce3a6cf8696ba4a6f

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d47e939c79d633ba9f591bacf51f34f3d5950ea9
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: c617ccc7e7ec2bd8c1b952fd29dad7cfdad6b395

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: d771eff57ac66390a21bf42ed739bf4401245c94
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: 1aceb342b06dcd69f85813896c46e41c6e6d7977

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: f11d730dc8f40847e5db24f04e566786ce422559
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: 51a5414e1ea889322c7bc30d6d56e74a3f12925d

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 19eceb306bb90eda702a8e494992e77a047f9e5f
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: 7783213fd0f6be45bbaeefa47db34503846ad672

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Agateo

##### Revision
Origin: 52e5967f44f7e1e1fa9187c5c9d8a08651a3cb17
Pull Request: 1fb38b1ee18e5c252eeb425883533755753f2b82
Server: 05cfa1d6c63b0d6a14d4c15d54d7e890c4986936

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: 8e319901f1cc7d151100c14c45028a6f1cf3c67a
Pull Request: 9818c51b817d1ef63cc5821e2a7b8094ca893f4c
Server: 55960fd6585c69e06d5526982d8f06b8906dfe45

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: d81c23dc885d585bcf86c8071e7988b3f51604c7
Pull Request: 9818c51b817d1ef63cc5821e2a7b8094ca893f4c
Server: e9e2dac000c0529406bcdf6b0be2adfdd0d35f0b

##### Comment

</details>

**Review by Agateophobia — APPROVED** [review]
This seems fine, testmerging didn't produce any negative feedback. Worst case scenario we will readjust it. Merged.

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: a116d7a3a557a5ee636b3d74e8751b10086fe176
Pull Request: 9818c51b817d1ef63cc5821e2a7b8094ca893f4c
Server: 0cbaaeba01f9c96ff58eff6e3396276888e55aab

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucia

##### Revision
Origin: dc0fdc04c3ff089b81c61f11ab55b723dd9dbefa
Pull Request: 9818c51b817d1ef63cc5821e2a7b8094ca893f4c
Server: ef9e8078c16ef0005fbcf7295b93d4d13bc5f54e

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Removed

**Pull request merged**
