### PR TITLE
Anchors rework

### PR DESCRIPTION
**Pull request by Discozavisim**
## About The Pull Request

image
image

## Why It's Good For The Game

Good

## Changelog
:cl:
add: More information about your lovers, friends, and enemies! They can now choose what information to give you, and you know their cellphone number!
/:cl:

### CODE REVIEW

**Comment by lucifernix** [comment]
I'll testmerge this because it needs to be tested by more people.

**Comment by wod13-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 54805d06ce3945485971036c60b3d6fd58a11892
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: 41590c328a83099cd05c8c413da70a1e86fa91ab

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 70b13d9b47b57a78ec12caa58d6e9fd9ef143522
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: c5c52c488fece15d40dc03c64e8b6816667b30ff

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: f06b41d3584b0615e9dae615b0c663538136a797
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: 5ebf41506e65934d7b20f5f87325b7add4c7d47b

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 40c9cb0c013b196f2ab869db4a001bca348c4936
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: ec372cca9b3c688805cf6925f14e55a7fd84acfb

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 102bd16616cb7800f6d94f9aacafd4b5a53680db
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: 104a01e5e4232a6568a75d1d134278853e915d30

##### Comment

</details>

**Comment by wod13-server** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Live Server

##### Merged By
Lucifernix

##### Revision
Origin: 514bf3c36b948776d82d7ef1860e57127e85d31e
Pull Request: d78e0f52b56e2b18c76d1aa0e495253981a28a02
Server: b3102dcee9aea27c51dcd7ca5cac1b7a20667656

##### Comment

</details>

**Pull request merged**
